/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.uc10_atividade03_barbararezei;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class cadastrarlogin extends javax.swing.JFrame {
    

    /**
     * Creates new form cadastrarlogin
     */
    public cadastrarlogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pacrespbuttongroup = new javax.swing.ButtonGroup();
        casdastrologin = new javax.swing.JPanel();
        imagempanel = new javax.swing.JScrollPane();
        imagemtextfield = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        senhatext = new javax.swing.JLabel();
        nometextfield = new javax.swing.JTextField();
        usuariotext = new javax.swing.JLabel();
        senhatextfield = new javax.swing.JTextField();
        pacienteradionbutton = new javax.swing.JRadioButton();
        responsavelradionbutton = new javax.swing.JRadioButton();
        cadastrarbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        imagemtextfield.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        imagemtextfield.setText("                 imagem");
        imagempanel.setViewportView(imagemtextfield);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("SINTOMA SAUDE ");

        senhatext.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        senhatext.setText("SENHA");

        nometextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nometextfieldActionPerformed(evt);
            }
        });

        usuariotext.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        usuariotext.setText("NOME USUARIO:");

        senhatextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhatextfieldActionPerformed(evt);
            }
        });

        pacrespbuttongroup.add(pacienteradionbutton);
        pacienteradionbutton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pacienteradionbutton.setText("É PACIENTE");

        pacrespbuttongroup.add(responsavelradionbutton);
        responsavelradionbutton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        responsavelradionbutton.setText("É RESPONSAVEL POR UM PACIENTE ");

        cadastrarbutton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cadastrarbutton.setText("CADASTRAR");
        cadastrarbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout casdastrologinLayout = new javax.swing.GroupLayout(casdastrologin);
        casdastrologin.setLayout(casdastrologinLayout);
        casdastrologinLayout.setHorizontalGroup(
            casdastrologinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(casdastrologinLayout.createSequentialGroup()
                .addComponent(imagempanel, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(casdastrologinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(casdastrologinLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1))
                    .addGroup(casdastrologinLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(casdastrologinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(casdastrologinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(usuariotext)
                                .addComponent(nometextfield)
                                .addComponent(senhatext)
                                .addComponent(senhatextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
                            .addGroup(casdastrologinLayout.createSequentialGroup()
                                .addComponent(pacienteradionbutton)
                                .addGap(18, 18, 18)
                                .addGroup(casdastrologinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cadastrarbutton)
                                    .addComponent(responsavelradionbutton))))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        casdastrologinLayout.setVerticalGroup(
            casdastrologinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagempanel)
            .addGroup(casdastrologinLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(57, 57, 57)
                .addComponent(usuariotext)
                .addGap(18, 18, 18)
                .addComponent(nometextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(senhatext)
                .addGap(18, 18, 18)
                .addComponent(senhatextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(casdastrologinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pacienteradionbutton)
                    .addComponent(responsavelradionbutton))
                .addGap(41, 41, 41)
                .addComponent(cadastrarbutton)
                .addGap(0, 98, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(casdastrologin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(casdastrologin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nometextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nometextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nometextfieldActionPerformed

    private void senhatextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhatextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhatextfieldActionPerformed

    private void cadastrarbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarbuttonActionPerformed
        // TODO add your handling code here:
        
        usuario us = new usuario();
        us.setLogin(nometextfield.getText());
        us.setSenha(senhatextfield.getText());
        
        if(pacienteradionbutton.isSelected())
        {
            us.setTipo("paciente");
        }
        else if(responsavelradionbutton.isSelected())
        {
            us.setTipo("responsavel");
        }
        
        usuarioJPA.cadastrar(us);
        
    
    
    JOptionPane.showMessageDialog(null, "Usuario cadastrado com sucesso!!!!!!");
        
        
    }//GEN-LAST:event_cadastrarbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastrarlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastrarlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastrarlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastrarlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastrarlogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarbutton;
    private javax.swing.JPanel casdastrologin;
    private javax.swing.JScrollPane imagempanel;
    private javax.swing.JLabel imagemtextfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nometextfield;
    private javax.swing.JRadioButton pacienteradionbutton;
    private javax.swing.ButtonGroup pacrespbuttongroup;
    private javax.swing.JRadioButton responsavelradionbutton;
    private javax.swing.JLabel senhatext;
    private javax.swing.JTextField senhatextfield;
    private javax.swing.JLabel usuariotext;
    // End of variables declaration//GEN-END:variables
}
