/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.uc10_atividade03_barbararezei;

import java.util.List;

/**
 *
 * @author Usuario
 */
public class especificacoes extends javax.swing.JFrame {

    /**
     * Creates new form especificacoes
     */
    public especificacoes() {
        initComponents();
        
    }
    
   public especificacoes(usuario u )
   {
       if (u.getTipo().equalsIgnoreCase("paciente"))
       {
           responsavelcadtext.setEnabled(false);
           nomeresptext.setEnabled(false);
           nomeresptextfield.setEnabled(false);
           paciresptextfield.setEnabled(false);
           nomepesqtextfield.setEnabled(false);
           cadarespbutton.setEnabled(false);
       }
       else if(u.getTipo().equalsIgnoreCase("responsavel"))
       {
           responsavelcadtext.setEnabled(true);
           nomeresptext.setEnabled(true);
           nomeresptextfield.setEnabled(true);
           paciresptextfield.setEnabled(true);
           nomepesqtextfield.setEnabled(true);
           cadarespbutton.setEnabled(true);
       }
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        especificacoespanel = new javax.swing.JPanel();
        imagempanel = new javax.swing.JScrollPane();
        imagemtext = new javax.swing.JLabel();
        nometext = new javax.swing.JLabel();
        nometextfield = new javax.swing.JTextField();
        sintomasaudetext = new javax.swing.JLabel();
        pacientetext = new javax.swing.JLabel();
        nometext1 = new javax.swing.JLabel();
        idadetextfield = new javax.swing.JTextField();
        condicaotext = new javax.swing.JLabel();
        condicaotextfield = new javax.swing.JTextField();
        condicaotext1 = new javax.swing.JLabel();
        remediotextfield = new javax.swing.JTextField();
        inftext = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inftextarea = new javax.swing.JTextArea();
        pacicadastrar = new javax.swing.JButton();
        responsavelcadtext = new javax.swing.JLabel();
        nomeresptext = new javax.swing.JLabel();
        nomeresptextfield = new javax.swing.JTextField();
        paciresptextfield = new javax.swing.JLabel();
        nomepesqtextfield = new javax.swing.JTextField();
        cadarespbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        imagemtext.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        imagemtext.setText("                      imagem");
        imagempanel.setViewportView(imagemtext);

        nometext.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nometext.setText("NOME:");

        sintomasaudetext.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        sintomasaudetext.setText("SINTOMA SAUDE ");

        pacientetext.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pacientetext.setText("CADASTRAR PACIENTE");

        nometext1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nometext1.setText("IDADE:");

        condicaotext.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        condicaotext.setText("CONDIÇÃO");

        condicaotextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                condicaotextfieldActionPerformed(evt);
            }
        });

        condicaotext1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        condicaotext1.setText("REMEDIO:");

        inftext.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        inftext.setText("INFORMAÇÕES SOBRE O REMEDIO ");

        inftextarea.setColumns(20);
        inftextarea.setRows(5);
        jScrollPane1.setViewportView(inftextarea);

        pacicadastrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pacicadastrar.setText("CADASTRAR PACIENTE");
        pacicadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacicadastrarActionPerformed(evt);
            }
        });

        responsavelcadtext.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        responsavelcadtext.setText("CADASTRAR RESPONSAVEL");

        nomeresptext.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nomeresptext.setText("NOME");

        paciresptextfield.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        paciresptextfield.setText("NOME PACIENTE:");

        cadarespbutton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cadarespbutton.setText("CADASTRAR RESPONSAVEL ");
        cadarespbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadarespbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout especificacoespanelLayout = new javax.swing.GroupLayout(especificacoespanel);
        especificacoespanel.setLayout(especificacoespanelLayout);
        especificacoespanelLayout.setHorizontalGroup(
            especificacoespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(especificacoespanelLayout.createSequentialGroup()
                .addComponent(imagempanel, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(especificacoespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(especificacoespanelLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(especificacoespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(especificacoespanelLayout.createSequentialGroup()
                                .addComponent(condicaotext)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(condicaotextfield))
                            .addGroup(especificacoespanelLayout.createSequentialGroup()
                                .addGroup(especificacoespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(especificacoespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(especificacoespanelLayout.createSequentialGroup()
                                            .addComponent(condicaotext1)
                                            .addGap(18, 18, 18)
                                            .addComponent(remediotextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE))
                                        .addGroup(especificacoespanelLayout.createSequentialGroup()
                                            .addGroup(especificacoespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(nometext1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(nometext, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(especificacoespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(nometextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                                                .addComponent(idadetextfield))))
                                    .addComponent(inftext)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(17, 17, 17))
                    .addGroup(especificacoespanelLayout.createSequentialGroup()
                        .addGroup(especificacoespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(especificacoespanelLayout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(pacicadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(especificacoespanelLayout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addGroup(especificacoespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pacientetext)
                                    .addComponent(sintomasaudetext)))
                            .addGroup(especificacoespanelLayout.createSequentialGroup()
                                .addGap(154, 154, 154)
                                .addComponent(responsavelcadtext))
                            .addGroup(especificacoespanelLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(especificacoespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(especificacoespanelLayout.createSequentialGroup()
                                        .addComponent(paciresptextfield)
                                        .addGap(18, 18, 18)
                                        .addComponent(nomepesqtextfield))
                                    .addGroup(especificacoespanelLayout.createSequentialGroup()
                                        .addComponent(nomeresptext)
                                        .addGap(18, 18, 18)
                                        .addComponent(nomeresptextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, especificacoespanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cadarespbutton)
                        .addGap(124, 124, 124))))
        );
        especificacoespanelLayout.setVerticalGroup(
            especificacoespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagempanel)
            .addGroup(especificacoespanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(sintomasaudetext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pacientetext)
                .addGap(44, 44, 44)
                .addGroup(especificacoespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nometext)
                    .addComponent(nometextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(especificacoespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nometext1)
                    .addComponent(idadetextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(especificacoespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(condicaotext)
                    .addComponent(condicaotextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(especificacoespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(condicaotext1)
                    .addComponent(remediotextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(inftext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pacicadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(responsavelcadtext)
                .addGap(30, 30, 30)
                .addGroup(especificacoespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeresptext)
                    .addComponent(nomeresptextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(especificacoespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paciresptextfield)
                    .addComponent(nomepesqtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(cadarespbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(especificacoespanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(especificacoespanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void condicaotextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_condicaotextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_condicaotextfieldActionPerformed

    private void pacicadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacicadastrarActionPerformed
        // TODO add your handling code here:
        paciente pa = new paciente();
        pa.setNome(nometextfield.getText());
        pa.setIdade(idadetextfield.getText());
        pa.setCondicao(condicaotextfield.getText());
        pa.setRemedio(remediotextfield.getText());
        pa.setInfremedio(inftextarea.getText());
        
        pacientecadastrar.cadastrar(pa);
        
    }//GEN-LAST:event_pacicadastrarActionPerformed

    private void cadarespbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadarespbuttonActionPerformed
        // TODO add your handling code here:
        paciente pa = new paciente();
        responsavel res = new responsavel();
        pacientecadastrar paj = new pacientecadastrar();
        pacientebuscarid idp = new pacientebuscarid();
        
         String pegarnome = nomepesqtextfield.getText();
         
         int idpaciente = idp.buscarIdPorNome(pegarnome);
         
         
         res.setNome(nomeresptextfield.getText());
         res.setIdpaciente(idpaciente);
         
         responsavelJPA.cadastrar(res);
         
         
         

        
        
    }//GEN-LAST:event_cadarespbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(especificacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(especificacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(especificacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(especificacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new especificacoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadarespbutton;
    private javax.swing.JLabel condicaotext;
    private javax.swing.JLabel condicaotext1;
    private javax.swing.JTextField condicaotextfield;
    private javax.swing.JPanel especificacoespanel;
    private javax.swing.JTextField idadetextfield;
    private javax.swing.JScrollPane imagempanel;
    private javax.swing.JLabel imagemtext;
    private javax.swing.JLabel inftext;
    private javax.swing.JTextArea inftextarea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomepesqtextfield;
    private javax.swing.JLabel nomeresptext;
    private javax.swing.JTextField nomeresptextfield;
    private javax.swing.JLabel nometext;
    private javax.swing.JLabel nometext1;
    private javax.swing.JTextField nometextfield;
    private javax.swing.JButton pacicadastrar;
    private javax.swing.JLabel pacientetext;
    private javax.swing.JLabel paciresptextfield;
    private javax.swing.JTextField remediotextfield;
    private javax.swing.JLabel responsavelcadtext;
    private javax.swing.JLabel sintomasaudetext;
    // End of variables declaration//GEN-END:variables
}
