/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.uc10_atividade03_barbararezei;

/**
 *
 * @author Usuario
 */
public class incidentetela extends javax.swing.JFrame {

    /**
     * Creates new form incidentetela
     */
    public incidentetela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        incidentepanel = new javax.swing.JPanel();
        imagempanel = new javax.swing.JScrollPane();
        imagemtext = new javax.swing.JLabel();
        sintomasaudetext = new javax.swing.JLabel();
        nometext = new javax.swing.JLabel();
        nometextfield = new javax.swing.JTextField();
        datatext = new javax.swing.JLabel();
        datatextfield = new javax.swing.JTextField();
        horatext = new javax.swing.JLabel();
        horatextfield = new javax.swing.JTextField();
        sintomatext = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sintomatextarea = new javax.swing.JTextArea();
        registrobutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        imagemtext.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        imagemtext.setText("                imagem");
        imagempanel.setViewportView(imagemtext);

        sintomasaudetext.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        sintomasaudetext.setText("sintoma saude ");

        nometext.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nometext.setText("NOME PACIENTE:");

        datatext.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        datatext.setText("DATA:");

        horatext.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        horatext.setText("HORA:");

        sintomatext.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sintomatext.setText("SINTOMAS:");

        sintomatextarea.setColumns(20);
        sintomatextarea.setRows(5);
        jScrollPane1.setViewportView(sintomatextarea);

        registrobutton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        registrobutton.setText("REGISTRAR");
        registrobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrobuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout incidentepanelLayout = new javax.swing.GroupLayout(incidentepanel);
        incidentepanel.setLayout(incidentepanelLayout);
        incidentepanelLayout.setHorizontalGroup(
            incidentepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(incidentepanelLayout.createSequentialGroup()
                .addComponent(imagempanel, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(incidentepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(incidentepanelLayout.createSequentialGroup()
                        .addGroup(incidentepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(incidentepanelLayout.createSequentialGroup()
                                .addGap(198, 198, 198)
                                .addComponent(sintomasaudetext))
                            .addGroup(incidentepanelLayout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addGroup(incidentepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sintomatext)
                                    .addGroup(incidentepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(incidentepanelLayout.createSequentialGroup()
                                            .addComponent(horatext)
                                            .addGap(18, 18, 18)
                                            .addComponent(horatextfield))
                                        .addGroup(incidentepanelLayout.createSequentialGroup()
                                            .addComponent(datatext)
                                            .addGap(18, 18, 18)
                                            .addComponent(datatextfield))
                                        .addGroup(incidentepanelLayout.createSequentialGroup()
                                            .addComponent(nometext)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(nometextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 112, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, incidentepanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(registrobutton)
                        .addGap(265, 265, 265))))
        );
        incidentepanelLayout.setVerticalGroup(
            incidentepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagempanel)
            .addGroup(incidentepanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sintomasaudetext)
                .addGap(48, 48, 48)
                .addGroup(incidentepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nometext)
                    .addComponent(nometextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(incidentepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datatext)
                    .addComponent(datatextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(incidentepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(horatext)
                    .addComponent(horatextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(sintomatext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(registrobutton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(incidentepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(incidentepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void registrobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrobuttonActionPerformed
        // TODO add your handling code here:
        paciente pa = new paciente();
        incidente in = new incidente();
        pacientecadastrar paj = new pacientecadastrar();
        pacientebuscarid idp = new pacientebuscarid();
        
        String pegarnome = nometextfield.getText();
        
        int idpaciente = idp.buscarIdPorNome(pegarnome);
        
        in.setIdpaciente(idpaciente);
        in.setData(datatextfield.getText());
        in.setHora(horatextfield.getText());
        in.setRelato(sintomatextarea.getText());
        
        /**incidentecadastrar.cadastrar(in);
         * codigo mudado apenas para testes 
         */
    }//GEN-LAST:event_registrobuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(incidentetela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(incidentetela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(incidentetela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(incidentetela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new incidentetela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel datatext;
    private javax.swing.JTextField datatextfield;
    private javax.swing.JLabel horatext;
    private javax.swing.JTextField horatextfield;
    private javax.swing.JScrollPane imagempanel;
    private javax.swing.JLabel imagemtext;
    private javax.swing.JPanel incidentepanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nometext;
    private javax.swing.JTextField nometextfield;
    private javax.swing.JButton registrobutton;
    private javax.swing.JLabel sintomasaudetext;
    private javax.swing.JLabel sintomatext;
    private javax.swing.JTextArea sintomatextarea;
    // End of variables declaration//GEN-END:variables
}
