/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.uc10_atividade03_barbararezei;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class logintela extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public logintela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginpanel = new javax.swing.JPanel();
        logintextfield = new javax.swing.JLabel();
        IMAGEMPANEL = new javax.swing.JScrollPane();
        imagemteztfield = new javax.swing.JLabel();
        usuariotext = new javax.swing.JLabel();
        usuariotextfield = new javax.swing.JTextField();
        senhatext = new javax.swing.JLabel();
        senhatextfield = new javax.swing.JTextField();
        entrarbutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cadastrarbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        logintextfield.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        logintextfield.setText("SINTOMA SAUDE");

        imagemteztfield.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        imagemteztfield.setText("           imagem ");
        IMAGEMPANEL.setViewportView(imagemteztfield);

        usuariotext.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        usuariotext.setText("USUARIO:");

        senhatext.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        senhatext.setText("SENHA");

        entrarbutton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        entrarbutton.setText("ENTRAR");
        entrarbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarbuttonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("NÃO POSSUI CADASTRO AINDA? CLIQUE AQUI:");

        cadastrarbutton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cadastrarbutton.setText("CADASTRAR");
        cadastrarbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginpanelLayout = new javax.swing.GroupLayout(loginpanel);
        loginpanel.setLayout(loginpanelLayout);
        loginpanelLayout.setHorizontalGroup(
            loginpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginpanelLayout.createSequentialGroup()
                .addComponent(IMAGEMPANEL, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(loginpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginpanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1))
                    .addGroup(loginpanelLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(cadastrarbutton))
                    .addGroup(loginpanelLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(loginpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usuariotext)
                            .addComponent(usuariotextfield)
                            .addComponent(senhatext)
                            .addComponent(senhatextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(loginpanelLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(logintextfield))))
                    .addGroup(loginpanelLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(entrarbutton)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        loginpanelLayout.setVerticalGroup(
            loginpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginpanelLayout.createSequentialGroup()
                .addComponent(logintextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(usuariotext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usuariotextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(senhatext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(senhatextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(entrarbutton)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(73, 73, 73)
                .addComponent(cadastrarbutton)
                .addGap(0, 115, Short.MAX_VALUE))
            .addComponent(IMAGEMPANEL)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void entrarbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarbuttonActionPerformed
        // TODO add your handling code here:
        usuario u = new usuario();
        u.setLogin(usuariotextfield.getText());
        u.setSenha(senhatextfield.getText());
        
        u = usuarioJPA.validarusuario(u);
        
        if(u != null)
        {
            JOptionPane.showMessageDialog(null, "usuario autenticado com sucesso ");
            telaescolha tel = new telaescolha();
            tel.setVisible(true);
        }
         
    
    }//GEN-LAST:event_entrarbuttonActionPerformed

    private void cadastrarbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarbuttonActionPerformed
        // TODO add your handling code here:
        cadastrarlogin cad = new cadastrarlogin();
        cad.setVisible(true);
       
    }//GEN-LAST:event_cadastrarbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(logintela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(logintela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(logintela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(logintela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new logintela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane IMAGEMPANEL;
    private javax.swing.JButton cadastrarbutton;
    private javax.swing.JButton entrarbutton;
    private javax.swing.JLabel imagemteztfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel loginpanel;
    private javax.swing.JLabel logintextfield;
    private javax.swing.JLabel senhatext;
    private javax.swing.JTextField senhatextfield;
    private javax.swing.JLabel usuariotext;
    private javax.swing.JTextField usuariotextfield;
    // End of variables declaration//GEN-END:variables
}
