/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.uc10_atividade03_barbararezei;

/**
 *
 * @author Usuario
 */
public class telaescolha extends javax.swing.JFrame {

    /**
     * Creates new form telaescolha
     */
    public telaescolha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escolherpanel = new javax.swing.JPanel();
        imagempanel = new javax.swing.JScrollPane();
        imagemtext = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        especificaobutton = new javax.swing.JButton();
        registrobutton = new javax.swing.JButton();
        tabelasbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        imagemtext.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        imagemtext.setText("                  imagem");
        imagempanel.setViewportView(imagemtext);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("BEM VINDO AO SINTOMA SAUDE");

        especificaobutton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        especificaobutton.setText("ESPECIFICAÇÕES");
        especificaobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especificaobuttonActionPerformed(evt);
            }
        });

        registrobutton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        registrobutton.setText("REGISTRO DO INCIDENTE");
        registrobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrobuttonActionPerformed(evt);
            }
        });

        tabelasbutton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tabelasbutton.setText("TABELAS DE INFORMAÇÃO");
        tabelasbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabelasbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout escolherpanelLayout = new javax.swing.GroupLayout(escolherpanel);
        escolherpanel.setLayout(escolherpanelLayout);
        escolherpanelLayout.setHorizontalGroup(
            escolherpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escolherpanelLayout.createSequentialGroup()
                .addComponent(imagempanel, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(escolherpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(escolherpanelLayout.createSequentialGroup()
                        .addGroup(escolherpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(escolherpanelLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jLabel1))
                            .addGroup(escolherpanelLayout.createSequentialGroup()
                                .addGap(174, 174, 174)
                                .addComponent(especificaobutton)))
                        .addGap(0, 105, Short.MAX_VALUE))
                    .addGroup(escolherpanelLayout.createSequentialGroup()
                        .addGroup(escolherpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(escolherpanelLayout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addComponent(registrobutton))
                            .addGroup(escolherpanelLayout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(tabelasbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        escolherpanelLayout.setVerticalGroup(
            escolherpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escolherpanelLayout.createSequentialGroup()
                .addComponent(imagempanel, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(escolherpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(86, 86, 86)
                .addComponent(especificaobutton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(registrobutton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addComponent(tabelasbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escolherpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escolherpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void especificaobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especificaobuttonActionPerformed
        // TODO add your handling code here:
        especificacoes es = new especificacoes();
        es.setVisible(true);
    }//GEN-LAST:event_especificaobuttonActionPerformed

    private void registrobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrobuttonActionPerformed
        // TODO add your handling code here:
        incidentetela in = new incidentetela();
        in.setVisible(true);
    }//GEN-LAST:event_registrobuttonActionPerformed

    private void tabelasbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabelasbuttonActionPerformed
        // TODO add your handling code here:
        tabelas ta = new tabelas();
        ta.setVisible(true);
        
    }//GEN-LAST:event_tabelasbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaescolha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaescolha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaescolha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaescolha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaescolha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel escolherpanel;
    private javax.swing.JButton especificaobutton;
    private javax.swing.JScrollPane imagempanel;
    private javax.swing.JLabel imagemtext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton registrobutton;
    private javax.swing.JButton tabelasbutton;
    // End of variables declaration//GEN-END:variables
}
